### ISSUE TITLE
Build the same Docker file with different base images

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/r-4-duckdb#1]
@wael-sadek: This project showcases a bug, I'd like to understand if it occurs only on R 4.0 or also on other versions of R. For this, I'd like to build this image for multiple R versions, and push these versions to GHCR. Can you please help me set this up?

Only the first line of `Dockerfile` needs modification:

https://github.com/krlmlr/r-4-duckdb/blob/257c4cd23be34c091ce0942792ff1943244e4af7/Dockerfile#L1

We want:

- 4.0.5 (as is)
- 4.1.3
- 4.2.3
- 4.3.3

Thanks!

**Comment by krlmlr** [comment]
I switched to R 4.3.3 as a smoke test, let's see if the problem still occurs there. I'd still be interested in a solution to this problem.

**Comment by krlmlr** [comment]
It looks like all packages are written with the same tag: https://github.com/krlmlr/r-4-duckdb/pkgs/container/r-4-duckdb/versions

Do we need to differentiate? The image with R 4.3.3 should be built with "latest", and all images including 4.3.3 should be accessible with their respective version number.

**Comment by wael-sadek** [comment]
Tags are looking good, closing.
